apiVersion: v2
appVersion: 1.5.0
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami/
  version: 1.7.1
description: Tiny Go webserver that prints os information and HTTP request to output
home: https://github.com/containous/whoami
maintainers:
- email: sebastien.prudhomme@gmail.com
  name: sebastien-prudhomme
name: whoami
version: 2.5.0
